label LCPI-PC-T113
    kernel /boot/zImage
    devicetree /boot/sun8i-t113s-lcpi-pc-t113.dtb
    append console=ttyS3,115200 root=/dev/mmcblk0p1 rootwait panic=10 quiet loglevel=3 consoleblank=0 vt.global_cursor_default=0 ${extra}
